---
- hosts: all
  name: KERNEL
  become: true
  tasks:
    - name: IMPORT ELREPO KEY
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    - name: INSTALL ELREPO
      yum:
        name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
        state: present
