---
- hosts: all
  name: KERNEL
  become: true
  tasks:
    - name: IMPORT ELREPO KEY
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    - name: INSTALL ELREPO
      yum:
        name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
        state: present

    - name: ENABLE ELREPO KERNEL
      shell: yum-config-manager --enable elrepo-kernel

    - name: CHANGE DEFAULT KERNEL TO KERNEL-ML
      copy:
        src: ./etc/sysconfig/kernel
        dest: /etc/sysconfig/kernel

    - name: REMOVE OLD KERNEL HEADERS AND TOOLS
      yum:
        name:
          - kernel-headers
          - kernel-tools
          - kernel-tools-libs
        state: absent

    - name: INSTALL KERNEL-ML
      yum:
        name:
          - kernel-ml
          - kernel-ml-headers
          - kernel-ml-tools

    - name: REBOOT TO TEST KERNEL
      reboot:
